name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'  # Only trigger when web folder changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create docs directory
        run: |
          rm -rf docs
          mkdir -p docs
      
      - name: Copy web content to docs
        run: |
          cp -r web/* docs/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true  # Make sure to use a clean deployment