name: Deploy static content to GitHub Pages

on:
  push:
    branches: ["main"]  # Déploie à chaque push sur main
  workflow_dispatch:      # Permet aussi le déclenchement manuel

permissions:
  contents: read          # Lecture du dépôt
  pages: write            # Nécessaire pour déployer
  id-token: write         # Auth GitHub Pages

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Disable Jekyll
        run: echo "" > web/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4