networks:
  traefik_proxy:
    external: true
  ledmatrix:

services:
  lexmatrix:
    image: nginx:alpine
    container_name: ledmatrix
    labels:
      - traefik.enable=true
      - traefik.http.services.ledmatrix.loadbalancer.server.port=80
      - traefik.http.routers.ledmatrix.entrypoints=websecure
      - traefik.http.routers.ledmatrix.rule=Host(`ledmatrix.mchd.me`)
      - traefik.http.routers.ledmatrix.tls.certresolver=letsencrypt
    networks:
      - traefik_proxy
      - ledmatrix
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./js:/usr/share/nginx/html/js
      - ./css:/usr/share/nginx/html/css
      - ./drawings:/usr/share/nginx/html/drawings
      - ./images:/usr/share/nginx/html/images
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
